Navigation bar component
dotkom/galactic-thunderdome-x pull request #81
Opened 2022-03-30 16:42 UTC by Thomhas

2022-03-30 18:37 UTC, Thomhas commented
Closes: #82

2022-04-01 22:16 UTC, kharann requested changes

2022-04-01 22:16 UTC, kharann commented on .storybook/preview.tsx
> +function globalStyles() {
this will crash stuff in storybook. Remove this and import `src/theme/global-style.ts`

2022-04-01 22:16 UTC, kharann commented on .storybook/preview.tsx
> -import { globalCss } from "../src/theme/stitches.config";
change import to `/@/src/theme/global-style.ts`

2022-04-01 22:16 UTC, kharann commented on package.json
> +        "feather-icons": "^4.28.0",
you can get feather icons from react-icons

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/DesktopNavigation.tsx
> +export interface DesktopProps {
remove unused props

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/DesktopNavigation.tsx
> +export interface DesktopProps {
which means everything because you're not using them xd

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/DesktopNavigation.tsx
> +      <NavigationMenuItem>
Each menu item should generate from an object. This has a lot of repetitive code which can be simplified. Something like this perhaps?

```js
const tabs = [
  {
    name: "For Studenter",
    layout: "one",
    showOnMobile: false,
    Items: [{ title: "Webshop", link: "https://webshop.com", text: "Verdens best webshop"}, {...}]
  }
]
```

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/DesktopNavigation.tsx
> +      <NavigationMenuItem>
Each of these can probable be a component btw

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/MobileDropdown.tsx
> +const itemStyles = {
use the `css()` function from `@theme`. What's returned can directly be used with the `styled()` function

https://stitches.dev/docs/api#css

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/MobileDropdown.tsx
> +  ...itemStyles,
same as above

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/MobileDropdown.tsx
> +      <StyledContent sideOffset={5}>
can probably be simplified in a list of objects and using map

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/MobileDropdown.tsx
> +          css={{
inline css, split out and use createStyles

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/Navbar.tsx
> +  const changeNavbarColor = () => setColor("#fff");
lots of the navbar logic can probably be put in a custom hook.

https://reactjs.org/docs/hooks-custom.html

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/Navbar.tsx
> +      {/*TODO: Split into Mobile Navbar and Desktop Navbar components and use ternary operator*/}
do this todo

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/Navbar.tsx
> +      {/*TODO: Split into Mobile Navbar and Desktop Navbar components and use ternary operator*/}
probably pass in the tab items mentioned above so that mobile and desktop can share them somehow

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/Navbar.tsx
> +const MobileBox = styled("div", {
use the createStyles function?

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/components/desktop/DebugLink.tsx
> +const DebugLink = () => (
delete this file

2022-04-01 22:16 UTC, kharann commented on src/components/organisms/Navbar/components/desktop/StyledLink.tsx
> +};
use css() from `@theme`

2022-04-20 13:33 UTC, merged